version: '3.4'

services:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: universe
      MONGO_INITDB_DATABASE: iotworld
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./mongo-settings/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

 
  opdataapi:
    image:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
