input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][service]" => "%{service}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch-logs:9200"]
    index => "scoutpro-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
